[telegram]
api_id = 0
api_hash = ""

[tekegram.bot]
bot_token = "5272417495:AAFOvgZ7xz-Gebo_fCNai1DC7E6wy-yE_tE"
name = ""
username = ""
user_id = 0

[database]
database_url = ""

[settings]
owner = 0
sudo_users = []

[settings.commands]
prefix = ['!', '/']

[settings.log]
chat_id = 0

[settings.backup]
chat_id = 0

[api.stella]
api_key = ""
